# -*- coding: utf-8 -*-
"""Projeto_de_Calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzIZdWlQJqkEdYndFqzBL4v0WVFIL4Ov
"""

print('Bem vindo a Calculadora de valores do Restaurante!')

while True:

      #Receber os dois valores do usuário
      valor1 = float(input('Digite o valor do primeiro item: '))
      valor2 = float(input('Digite o valor do segundo item: '))


      #Menu de operações:
      print('\nEscolha qual operação deseja realizar: \n')
      print('1 - Soma dos valores (total de dois itens)')
      print('2 - Subtração dos valores (diferença entre dois itens ou desconto)')
      print('3 - Multiplicação dos valores (quantidade x preço)')
      print('4 - Divisão (preço médio)')
      print('5 - Sair do Programa!')

      escolha = input('Digite o número da operação desejada: ')


      #Realização da opção escolhida
      if escolha == '1':
        resultado = valor1 + valor2
        print('O resultado da soma é de R$: ' ,resultado)
      elif escolha == '2':
        resultado = valor1 - valor2
        print('A diferença entre os dois valores é de R$: ' ,resultado)
      elif escolha == '3':
        resultado = valor1 * valor2
        print('O resultado da multiplicação é de: ' ,resultado)

      elif escolha == '4':
        if valor2 == 0:
          print('Não é possível dividir por zero!')
        else: resultado = valor1 / valor2
        print('O preço médio dos itens é R$: ' ,resultado)
      elif escolha == '5':
        print('Fechando o programa...')
        break
      else:
        print('Opção inválida, tente novamente!')